In [2]:
import numpy as np

In [5]:
# Toy Example
graph = {}
graph[0] = [(4, 0.6), (3, 0.4)]
graph[1] = [(2, 0.3), (3, 0.7)]
graph[2] = [(1, 0.1), (0, 0.9)]
graph[3] = [(4, 0.4), (0, 0.6)]
graph[4] = [(1, 0.1), (3, 0.9)]

labels = np.array([0, 0, 0, 2, 1])

In [19]:
# Construct state transition matrix
num_states = 3

transition_matrix = np.zeros((num_states, num_states))
counts = np.zeros(num_states)
for src_frame, edge in graph.items():
    src_cluster = labels[src_frame]
    counts[src_cluster] = counts[src_cluster] + 1
    for sink_frame, prob in edge:
        sink_cluster = labels[sink_frame]
        transition_matrix[src_cluster][sink_cluster] = transition_matrix[src_cluster][sink_cluster] + prob
    
for i in range(num_states):
    transition_matrix[i, :] = transition_matrix[i, :]/counts[i]
print(transition_matrix)
print(count_matrix)

        

[[ 0.43333333  0.2         0.36666667]
 [ 0.1         0.          0.9       ]
 [ 0.6         0.4         0.        ]]
[[ 3.  1.  2.]
 [ 1.  0.  1.]
 [ 1.  1.  0.]]


In [17]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [ ]:
# Open Dictionary
import json
with open(foldername + dict_filename, 'r') as fp:
    raw_dict = json.load(fp)

# Read through the dictionary and fix all the tuples
edges  = {}
for key,value in raw_dict.items(): # not iteritems() since it's python 3.x
    edges[int(key)] = [(int(tup[0]), float(tup[1])) for tup in value]